version: 2.1
orbs:
  trigger-pipeline: sensu/trigger-pipeline@1.0.0


workflows:
  integration-test:
    jobs:
      - trigger-pipeline/trigger:
          slug: "github/rochecirclecipoc/rtables"
          branch: master
