version: 2.1
orbs:
  trigger-pipeline: rochecirclecipoc/trigger-pipeline@1.0.0


workflows:
  integration-test:
    jobs:
      - trigger-pipeline/trigger:
          name: rtables
          slug: "github/rochecirclecipoc/rtables"
          branch: master
      - trigger-pipeline/trigger:
          name: simpleR
          slug: "github/rochecirclecipoc/simpleR"
          requires:
            - rtables
      - trigger-pipeline/trigger:
          name: rbaseimage
          slug: "github/rochecirclecipoc/rbaseimage"
          requires:
            - simpleR
